x = 2*rnorm(500)
y = rnorm(500)
png('covex.png')
par(mfrow=c(2,2))
plot(x,y,xlab='',ylab='',pch=20,asp=1,main='(A)')
plot(y,x,xlab='',ylab='',pch=20,asp=1,main='(B)')
plot((x+y)/sqrt(2),(x-y)/sqrt(2),xlab='',ylab='',pch=20,asp=1,main='(C)')
plot((x+y)/sqrt(2),(y-x)/sqrt(2),xlab='',ylab='',pch=20,asp=1,main='(D)')
dev.off()
